- org.eclipse.bluesky/plugin.xml
- org.eclipse.bluesky/src/org/eclipse/bluesky/css/CSSLanguageServer.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/html/HTMLLanguageServer.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/json/JSonLanguageServer.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/json/JSonLanguageServerInterface.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/jsts/JSTSLanguageServer.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/jsts/debug/ToogleLineBreakpointHandler.java
This PR groups extension point declaration + package per language. It's the first step before splitting plugins per language https://github.com/mickaelistria/eclipse-bluesky/issues/26
> Group extension point declaration + package per language

- repository/pom.xml
> Fix tm4e url

- org.eclipse.bluesky/src/org/eclipse/bluesky/colors/ColorHelper.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/colors/ColorSymbolDrawingStrategy.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/colors/ColorSymbolSupport.java
This PR gives the capacity to choose a color with Color Dialog by clicking on the colorized square (see https://github.com/mickaelistria/eclipse-bluesky/issues/41)
Here a little demo:
> Choose color with ColorDialog by click on colorized square. See

- org.eclipse.bluesky/plugin.xml
Activate color symbol for less + scss.
Signed-off-by: angelozerr <angelo.zerr@gmail.com>
> Activate color symbol for less + scss.

- org.eclipse.bluesky/src/org/eclipse/bluesky/InitializeLaunchConfigurations.java
- org.eclipse.bluesky/src/org/eclipse/bluesky/jsts/debug/ToogleLineBreakpointHandler.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Use logger

- Jenkinsfile
> Issue #74 Set up builds on https://jenkins.eclipse.org/wildwebdeveloper/

- Jenkinsfile
> Bug 539991 - Try to add the known_hosts

- pom.xml
- repository/pom.xml
> Enable download.stats

- org.eclipse.wildwebdeveloper/language-servers/package.json
This adds the typescript NPM module as a declared dependency to package.json.
Fixes #88
Signed-off-by: Jonas Hungershausen <jonas.hungershausen@vogella.com>
> Fix: UI Freeze & Error: Cannot find module 'typescript' #88

- target-platform/target-platform.target
Signed-off-by: Gautier de Saint Martin Lacaze <dark.jabberwock+github@gmail.com>
> Issue #90 : Fix target platform in master

- org.eclipse.wildwebdeveloper/language-servers/package-lock.json
- org.eclipse.wildwebdeveloper/language-servers/package.json
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeRunDAPDebugDelegate.java
> Use newer node support from VSCode

- pom.xml
> Upgrade to Tycho 1.3

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper/plugin.xml
#120 
Signed-off-by: Xi Yan xixiyan@redhat.com
> Add DTD content type

- Jenkinsfile
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
> Add timeout to avoid hanging builds

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
> Show Run/Debug on Resources perspective

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
> Add dependency to org.eclipse.tm4e.languageconfiguration

- target-platform/target-platform.target
> Upgrade TP to 4.11/2019-03

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper/language-servers/package-lock.json
- org.eclipse.wildwebdeveloper/language-servers/package.json
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/AddShemaGlobPatternDialog.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLSchemaPreferencePage.java
#56 
This integrates https://github.com/redhat-developer/yaml-language-server, and adds a preference page to associate schemas.
> Integrate YAML LS

- README.md
Signed-off-by: Xi Yan <xixiyan@redhat.com>
> Add YAML video to README

- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
- repository/pom.xml
- target-platform/pom.xml
- target-platform/target-platform.target
> Update target platform to 4.11

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
- repository/category.xml
- target-platform/target-platform.target
> #149 Remove dependency to org.apache.commons.io

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebug.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/Utils.java
- org.eclipse.wildwebdeveloper.tests/testProjects/helloWorldJS/hello.js
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeRunDebugLaunchShortcut.java
> Added automated test for Debug

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper/plugin.xml
- target-platform/target-platform.target
> Make some Language Server singletons explicitly

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
- repository/pom.xml
- target-platform/pom.xml
Opens the stream for development.
> Bump version to 0.4.1.

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java
lsp4xml has a lot of new features and fixes so let's not delay on using
it as osgi lib.
> Update to lsp4xml 0.7.0

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebug.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestTypeScript.java
> Fix some illegal access warnings.

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLSchemaPreferencePage.java
> Use lambdas.

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
It is a simple implementation for #55 
If you have any suggestions, feel free to comment. I will update the PR accordingly.
> Fix #55 by adding a validation of supported node.js versions

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
Closes #196.
No need to spawn a new shell to run the `node -v` command: we already have an absolute path we can use directly. The command path will be escaped successfully in this case, and `-v` will be treated as a separate argument, rather than `C:\\Program Files\\nodejs\\node.exe -v` being understood as a single argument. There are still cases where `version` can be null (caught `IOException` or `readLine` returning null if no data is sent to stdout), so I added an extra check and warning in that case to avoid having a `NullPointerException`.
Signed-off-by: Pierre-Yves B. <PyvesDev@gmail.com>
> Improve handling of Node.js version validation

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/testProjects/angular-app/package-lock.json
- org.eclipse.wildwebdeveloper.tests/testProjects/angular-app/package.json
- org.eclipse.wildwebdeveloper.tests/testProjects/angular-app/tsconfig.json
- org.eclipse.wildwebdeveloper/language-servers/package-lock.json
- org.eclipse.wildwebdeveloper/language-servers/package.json
> Update to typescript 3.5.3 and ls 0.3.8.

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/TypeScriptPlugin.java
Fixes #180.
Signed-off-by: Pierre-Yves B. PyvesDev@gmail.com
> Convert file URLs to proper file paths

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper/language-servers/package-lock.json
- org.eclipse.wildwebdeveloper/language-servers/package.json
> Yaml LS update to 0.5.2

- org.eclipse.wildwebdeveloper/pom.xml
> Use npm ci instead of npm install

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/language-servers/package-lock.json
- org.eclipse.wildwebdeveloper/language-servers/package.json
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
- repository/pom.xml
- target-platform/pom.xml
> Use vscode-json-languageserver from npm

- target-platform/target-platform.target
Needed for generic editor icon extension point.
> Fix target platform to use 4.13 I-builds.

- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20609
> Update to lsp4xml 0.8.0

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
> Issue #220 - Enable support for node 11 and 12

- Jenkinsfile
- docker/Dockerfile
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebug.java
> [TEST/WIP] TestDebug shows more log

- repository/category.xml
Signed-Off-By: Mickael Istria <mistria@redhat.com>
> Re-label p2 categories

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/SelectionUtils.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxRunDebugLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/RunFirefoxDebugTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDebugLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/RunProgramTab.java
uses more heuristic to detect good default value in the Launch
Configuration dialog
+ Fix Firefox launch configuration not accessible from dialog
+ Refactoring on launch shortcut.
> Issue #244 - Pre-set launch configurations

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/HTMLLaunchableAdapterFactory.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/IsLaunchableHTMLTester.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxRunDABDebugDelegate.java
> Java projects shouldn't be able to launch with Firefox #248

- target-platform/target-platform.target
Signed-Off-By: Mickael Istria <mistria@redhat.com>
> Use final Platform 4.13 URL in TP

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/SelectionUtils.java
Really nothing much going on here: just a small detail I noticed in the code.
Signed-off-by: PyvesB <PyvesDev@gmail.com>
> Remove unused local variable

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
> Hide Angular log

- Jenkinsfile
- target-platform/target-platform.target
> Update to newer LSP4E release

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
> Use AngularLS from npmJs

- README.md
> [README] link to Chrome debugger demo

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java
Fixes CVE-2019-18213 and CVE-2019-18212
> LSP4XML 0.9.1

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxAttachDebugTabGroup.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxAttachTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/AttachTab.java
> Issue #295 - Document attach to Firefox

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/SelectionUtils.java
- pom.xml
> Don't use deprecated getWorkbench method.

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java
Use Eclipse Platform proxy settings from preferences with highest
priority, and complete unset properties by propagating system properties
passed to the launcher.
Change-Id: I065748f4635ee70a919803b14f92bc3f170fe1f9
> Issue #192 - proxy support

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/schema/xmllsExtension.exsd
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLExtensionRegistry.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLSClasspathExtensionProvider.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java
> Add m2e dependencies onto XML LS classpath

- org.eclipse.wildwebdeveloper.feature/feature.properties
Fixed
Signed-off-by: Wim Jongman <wim.jongman@remainsoftware.com>
> Feature description syntax error #319

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/Activator.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLExtensionRegistry.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
Mark it as x-friends with m2e for the moment to make explicit it's not
100% set in stone and we use m2e to consolidate it.
> Export package containing extension interface

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
> Issue #322 - do not show warning popups more than once

- org.eclipse.wildwebdeveloper/pom.xml
> Update language servers

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
> Bug #324 Remove support of nodejs 8 and 9

- README.md
- RELEASE_NOTES.md
> Add ESLint demo video in README and release notes

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/.settings/org.eclipse.core.resources.prefs
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/json/JSonLanguageServer.java
- pom.xml
- target-platform/target-platform.target
> Add editor support for .eslintrc

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
> Bug #315 - Force use of TypeScript non-polling watchers.

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestTypeScript.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
> Bug #315 - Use log file for angular LS if logToFile is enabled

- Jenkinsfile
- docker/Dockerfile
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
> Try using newer version of Fedora/Java/Node in CI

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxRunDABDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugDelegate.java
> Fix browser paths & DAB ID's

- org.eclipse.wildwebdeveloper/pom.xml
> Update Firefox debug adapter to 2.6.1

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugTabGroup.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDAPDebugDelegate.java
> Allow to define remote/local source mapping for node attach

- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/json/JSonLanguageServer.java
+ Add formatter initializeOptions to JSON LS
> Upgrade VSCode LS

- TIPS_and_FAQ.md
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
Enable sourceMaps in Chrome Launch Debug Delegate
> Add TypeScript website debug instructions to FAQ

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
> Issue #366 - InvalidPathException when path are quoted

- target-platform/target-platform.target
> Reference latest deps in Target Platform

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestTypeScript.java
- target-platform/target-platform.target
Signod-Off-By: Mickael Istria <mistria@redhat.com>
> Reference latest wikitext release

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
> Issue #279 - Test

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/LemminxClasspathExtensionProvider.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLExtensionRegistry.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
> Adopt Eclipse Lemminx

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
Please review, as I'm doing this blind. I don't have a dev-env for wildwebdeveloper set up.
> Issue #396: which() to inspect PATH environment var for executables

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractRunHTMLDebugTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeAttachDebugTabGroup.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeAttachTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeExecutableTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDebugLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDebugTabGroup.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/RunChromeDebugTab.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/messages.properties
> Issue #386 -Use browsers defined in General/Web Browser for debugging

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package-lock.json
- org.eclipse.wildwebdeveloper/.gitignore
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/build.properties
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/CSSLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxRunDABDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/HTMLLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/json/JSonLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/TypeScriptPlugin.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java
> Test for too long paths

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractRunHTMLDebugTab.java
> Use static fields directly.

- org.eclipse.wildwebdeveloper.xml/pom.xml
See https://github.com/eclipse/lemminx/blob/master/CHANGELOG.md#0111-march-25-2020
> Update LemMinX to 0.11.1

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/InitializationOptionsProvider.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLExtensionRegistry.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
- pom.xml
> New extension for LemMinX to define initialization options

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/build.properties
- org.eclipse.wildwebdeveloper.xml/plugin.properties
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/Messages.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLCatalogPreferencePage.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferencePage.java
Adds XML Catalogs Preference page
Issue: #139
> [XML] Preferences page for XML #139

- org.eclipse.wildwebdeveloper/.gitignore
- org.eclipse.wildwebdeveloper/pom.xml
The following LSs will be updated to the latest versions:
typescript@3.8.3
typescript-plugin-css-modules@2.3.0
yaml-language-server@0.8.0
firefox-debugadapter@2.8.0
typescript-eslint-language-service@3.0.0
eslint@7.1.0
@typescript-eslint/eslint-plugin@3.1.0
@typescript-eslint/parser@3.1.0
@angular/language-service@9.1.9
@angular/language-server@0.901.9
> Draft: [Waiting for CQ] Update language servers

- org.eclipse.wildwebdeveloper/.gitignore
- org.eclipse.wildwebdeveloper/pom.xml
The following vscode LSs will be updated to the latest versions:
vscode-json-languageserver-1.2.3
Other vscode updates:
node-debug2-1.42.2
> Draft: [Waiting for a CQ] Upgrade VSCode LS to 1.45.1

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebugTS.java
- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/.build/index.js
- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/.build/index.js.map
- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/index.ts
- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/package.json
- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/tsconfig.json
- org.eclipse.wildwebdeveloper/.gitignore
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/IsNodeProjectPropertyTester.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDebugLaunchShortcut.java
> Better support TypeScript debugging #144

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd
> Adopt LemMinX 0.12.0

- RELEASE_NOTES.md
- TIPS_and_FAQ.md
- org.eclipse.wildwebdeveloper.embedder.node/README.md
> Release Notes anf FAQ for NodeJS Embedder

- repository/category.xml
> Add Node.js embedder to p2 repo

- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
> No more popup when missing node.js #469

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLSchemaPreferencePage.java
> SWTError YAML Schemas preference page #472

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
> Use platform's XML content-type definition

- org.eclipse.wildwebdeveloper.feature/feature.xml
Change-Id: Iabed528082a98b533267c4a5221f4b0a2d96c81d
> Issue #469 - Make node.js embedder an optional inclusion

- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java
Fixes: #461
The PR provides dynamic schemas and WorkspaceFolder list configuration (by listening for the Preferences/Workspace changes respectively).
> Cannot use provided schemas #461

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
> Fix XML LS Preferebce Chage Listener setup

- org.eclipse.wildwebdeveloper.xml/pom.xml
Change-Id: I5d39720794095fcac0f4d6dbc064da2e7788e54f
> Move to LemMinX 0.13.1

- docker/Dockerfile
> Update image to has Java 11 as default one.

- Jenkinsfile
> Use Java 11 able container on CI

- pom.xml
> Build with Tycho 2.0.0

- org.eclipse.wildwebdeveloper/pom.xml
* Maven antrun to 3.0.0
* Exec to 3.0.0
> Update maven build plugins.

- target-platform/target-platform.target
> Extend target platform to allow running tests in workbench.

- org.eclipse.wildwebdeveloper/pom.xml
Those workarounds are not necessary any more as issues were fixed
upstream.
> Remove useless steps in build

- org.eclipse.wildwebdeveloper/pom.xml
> Upgrade to newer Angular Language Server

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestHTML.java
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/HTMLLanguageServer.java
> Fix HTML formatting enablement 

- repository/category.xml
Fixes 541
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Fix typo in site descriptor

- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/.classpath
- org.eclipse.wildwebdeveloper.xml/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
> Move to LemMinX 0.14.1

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/ESLintProj.ts
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package-lock.json
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package.json
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/tsconfig.json
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServerExtension.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
+ Remove typescript-eslint-language-service from deps
+ Remove eslint from deps
+ Update ESLint tests
> Try vscode-eslint-server

- RELEASE_NOTES.md
> Add change note regarding schema association preference page

- RELEASE_NOTES.md
- target-platform/target-platform.target
> Release 0.11.4

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
Fixes #592 
Change-Id: I238f29d94a7ae4f7b731f41dbd289ff8e2b69af6
Signed-off-by: BoykoAlex <aboyko@pivotal.io>
> Use Eclipse JVM to launch XML LS

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Fix missing non-externalized string by using direct naming #586

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
Fixes #601
Change-Id: Ide9f161ae5a29e81692faf15b6d571bbca8c82ff
Signed-off-by: BoykoAlex <aboyko@pivotal.io>
> Calculate JVM path via java.home sys property

- org.eclipse.wildwebdeveloper/pom.xml
> Update language servers from npmjs

- Jenkinsfile
> Use newer container for build

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
> To LemMinX 0.15.0

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
> Update Embedded Node.js Runtime to latest LTS version (v14.15.4)

- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
> Stop using deprecated tycho-source-feature-plugin.

- .github/workflows/windowsPR.yml
> Update windows PR action

- org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/InitializationOptionsProvider.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
> Better handle initializationOptions

- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
> Simplify code by using Set.of

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServerExtension.java
This adds the "openDoc" implementation of ESLint possible quickfixes
> Implemented "openDoc" to open the given url in an External browser

- org.eclipse.wildwebdeveloper/pom.xml
Signed-off-by: Johan Compagner <jcompagner@gmail.com>
> clean node_modules as a whole and only the package-lock.json in the root dir

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServerExtension.java
- repository/epp.product
For now just log this as a message that for a specific file the eslint library can't be initialized
> support for the noLibrary call to not let that be a exception of unsupported json request

- org.eclipse.wildwebdeveloper/plugin.xml
forgotten change in the previous commit.
Signed-off-by: Johan Compagner <jcompagner@gmail.com>
> AngularLanguageServer: AngularClient added to the extension point

- pom.xml
Signed-off-by: Johan Compagner <jcompagner@gmail.com>
> introduce a jgit.dirtyWorkingTree mvn property that can be overwritten through command line

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
> Avoid usage of InternalPlatform

- org.eclipse.wildwebdeveloper/pom.xml
> VSCode 1.54

- target-platform/target-platform.target
> Use LSP4E latest release

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.product.branding/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.product.branding/plugin.xml
- org.eclipse.wildwebdeveloper.product.branding/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- repository/epp.product
- repository/pom.xml
Version is visible with more details in the "Installed Software" tab of
Installation Details.
> Issue #665 - Remove version is about dialog

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
A JUnit test is added for the rename issue
Issue: #680 
> [tests] Refactoring throws fatal error #680

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
Refactoring throws fatal error #680
> Fix rename js ts identifier

- org.eclipse.wildwebdeveloper/pom.xml
> [build] Fix download links for MS Marketplace

- pom.xml
> [build] Update JarSigner plugin to 1.3.0

- pom.xml
> Build with latest Tycho and jarsigner

- org.eclipse.wildwebdeveloper/pom.xml
Update NPM modules to the following versions:
typescript@4.3.5
typescript-language-server@0.5.4
typescript-plugin-css-modules@3.4.0
firefox-debugadapter@2.9.4
yaml-language-server@0.19.2
@angular/language-server@11.2.14
> Update npm packages 

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLCatalogs.java
LemMinX only accepts file:/ URIs for catalog entries, so we try to
convert everything that's not a file.
> Resolve XML catalogs platform:/ URIs to file:/

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
- pom.xml
Fix Rename JS-TS Identifier Test
> Fix Rename JS-TS Identifier Test

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/.gitignore
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/.project
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/build.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- pom.xml
> Update Embedded Node.js Runtime to latest version (v.16.9.0)

- target-platform/target-platform.target
> Update to latest wikitext.

- .github/workflows/windowsPR.yml
> Windows verification build with NodeJS 16 run

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
> Update VSCode ESLint plugin to 2.2.2 (from 2.1.14) (server 2.1.14->2.1.25)

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
> Update Embedded Node.js Runtime to latest LTS version (v.16.13.0)

- .github/dependabot.yml
- .github/workflows/licensecheck.yml
- pom.xml
> Add dependabot .

- target-platform/target-platform.target
> Build against wikitext 3.0.42

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
> Fix warnings in ESLintClientImpl

- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package-lock.json
- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package.json
Details
CVE-2021-3807
Moderate severity
Vulnerable versions: > 2.1.1, < 5.0.1
Patched version: 5.0.1
ansi-regex is vulnerable to Inefficient Regular Expression Complexity
> A vulnerability found in eslint test project

- org.eclipse.wildwebdeveloper/pom.xml
vscode                         -> 1.63.2
node-debug2            1.42.5  -> 1.43.0
debugger-for-chrome    4.12.12 -> 4.13.0
> Update Vscode extensions

- org.eclipse.wildwebdeveloper.xml/pom.xml
this fixes a couple security issues linked to downloading remote resources.
- https://github.com/eclipse/lemminx/pull/1171
- https://github.com/eclipse/lemminx/pull/1174
and a critical bug when validation is disabled, using 100% CPU:
- https://github.com/eclipse/lemminx/issues/1175
> Update LemMinX to 0.19.1

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
> Do not specify --tsserver-path

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- repository/epp.product
- repository/pom.xml
@angular/language-server 13.2.0 --> 13.3.2
typescript 4.5.5 --> 4.6.4
typescript-language-server 0.9.5 --> 0.9.7
> Update TypeScript, TypeScript and Angular  LS

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/testProjects/angular-app/package.json
- org.eclipse.wildwebdeveloper/pom.xml
Package @angular/core (npm) < 11.0.5
> Cross site scripting in Angular #2

- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
And we shipt Node.js 16.x as our bundled.
The idea of static list of supported versions is plain wrong as we have
no idea which editor which version of Node.js supports it's best to
remove the static list and just say "recent" version is required when
using the "system" Node.
> NodeJSManager wrongly claims Node 16 is not supported

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
Fixes https://github.com/eclipse/wildwebdeveloper/issues/849
> Always validate schema

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularClientImpl.java
remove the now implemented notifyProgress in the super class
> fix for language servers background jobs keep hanging around. #851

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceConstants.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
XML: Closing tags should be included in the code folding range
Fixes #857
> XML: Closing tags should be included in the code folding range

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/Messages.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceConstants.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferencePage.java
Support for xml.downloadExternalResources.enabled
Fixes #781
> Support for xml.downloadExternalResources.enabled

- org.eclipse.wildwebdeveloper/language-configurations/javascript/javascript-language-configuration.jsonc
- org.eclipse.wildwebdeveloper/language-configurations/typescript/language-configuration.jsonc
- org.eclipse.wildwebdeveloper/plugin.xml
OnEnterRules support for js, ts files
> OnEnterRules support for js, ts files

- org.eclipse.wildwebdeveloper.xml/language-configurations/xml/xml.language-configuration.json
- org.eclipse.wildwebdeveloper.xml/language-configurations/xsl/xsl.language-configuration.json
> OnEnterRules support for XML

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- target-platform/target-platform.target
> Fix junit.jupiter.api resolve failed error

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
Test Result (2 failures / ±0)
org.eclipse.wildwebdeveloper.tests.TestLanguageServers.testTSFile
org.eclipse.wildwebdeveloper.tests.TestLanguageServers.testTSXFile
> Fix TesLanguageServers TS/TSX test cases

- org.eclipse.wildwebdeveloper/pom.xml
yaml-language-server 1.7.0  --> 1.10.0
> Update LSs & NPM Modules - yaml-language-server 1.10.0

- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.2.2  --> 2.2.6
eslint-server  2.1.25 --> 2.2.5
> Update LSs & NPM Modules - vscode-eslint 2.2.6

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
> Fix JUnit tests AllCleanupRule

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java
> Fix ESLint Test project setup

- org.eclipse.wildwebdeveloper/pom.xml
typescript                  4.6.4  --> 4.8.3
typescript-language-server  0.9.7  --> 1.2.0
@ angular/language-server   14.0.1 --> 14.2.0
> Update LSs & NPM Modules - typescript 4.8.3 and related

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServer.java
> Rollback ESLint Language Server change

- Jenkinsfile
Change memory settings: 4Gi -> 6Gi
Add error reporting options to mvn command
> Fix Jenkins file settings

- org.eclipse.wildwebdeveloper.tests/testProjects/HelloWorldTS/package.json
> Fixed Debug TS test project

- org.eclipse.wildwebdeveloper/pom.xml
Update Vscode extensions:
vscode 1.66.2 --> 1.72.0
> Update VSCode (v.1.72.0) extentions

- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node/pom.xml
- org.eclipse.wildwebdeveloper.product.branding/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.product.branding/pom.xml
- pom.xml
> Use tycho 3.1.0

- org.eclipse.wildwebdeveloper/pom.xml
typescript-language-server  2.0.0  --> 2.0.1
> Update LSs & NPM Modules - typescript-language-server 2.0.1

- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.72.1) extentions

- RELEASE_NOTES.md
> Release Notes for 0.15.1

- org.eclipse.wildwebdeveloper/pom.xml
typescript-language-server  2.0.1  --> 2.1.0
> Update LSs & NPM Modules - typescript-language-server 2.1.0

- RELEASING.md
Add Releasing Guide for committers
> Add Releasing Guide for committers

- org.eclipse.wildwebdeveloper/plugin.properties
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/HTMLLanguageClient.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/HTMLLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/autoinsert/HTMLAutoInsertReconciler.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLCompletionPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLFormatPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLHoverPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLPreferenceClientConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/preferences/HTMLValidationPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/ui/preferences/ProcessStreamConnectionProviderWithPreference.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/ui/preferences/Settings.java
> HTML preferences page

- README.md
> Promote RelaxNG support

- org.eclipse.wildwebdeveloper/plugin.properties
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/SchemaAssociationsPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/CSSLanguageClient.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/ui/preferences/Settings.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YamlLanguageClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/CustomTagsFieldEditor.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLCompletionPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLFormatPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLHoverPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/ui/preferences/YAMLValidationPreferencePage.java
YAML preferences
This PR provides all settings which manages YAML LS. I set to draft because I need to test if it works correctly, but you can try it.
> YAML preferences

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.12.0
> Update Embedded Node.js Runtime to latest LTS version (v.18.12.0)

- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.73.0) extentions

- repository/epp.product
- repository/pom.xml
- target-platform/target-platform.target
```
[ERROR] Failed to resolve target definition file:/home/jeremy/projects/wildwebdeveloper/target-platform/target-platform.target: Failed to load p2 metadata repository from location https://download.eclipse.org/mylyn/docs/releases/3.0.42/: No repository found at https://download.eclipse.org/mylyn/docs/releases/3.0.42. -> [Help 1]
```
> Fix target platform build error

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestNodeJsEmbedder.java
The order of directories probe for Node.js installation:
- Platform Install Location
- Platform User Location
- WWD Node bundle configuration location
Issue: #733
> Put embedded nodejs in eclipse folder #733

- .github/workflows/windowsPR.yml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/Messages.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLValidationPreferencePage.java
XMLValidationPreferencePage updated to have message properties for _On namespace encountered_, _On valid schema_, and _Hint_
> Issue #933

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/AttachTab.java
> Viewing "Running Node.js application" silently resets "Port" #950

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestNpmRun.java
- org.eclipse.wildwebdeveloper.tests/testProjects/envtest/package.json
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/npm/NpmLaunchDelegate.java
> "Launch NPM" ignores custom environment variables #949

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.74.0) extentions

- org.eclipse.wildwebdeveloper.tests/testProjects/angular-app/package.json
The test project is changed to use Angular v.15.0.3
> [test] Update angular-app test project to use Angular v.15.0.3

- org.eclipse.wildwebdeveloper/plugin.xml
Uncomment org.eclipse.wildwebdeveloper.eslint.ESLintLanguageServer
In my last commit, I uncomment Uncomment org.eclipse.wildwebdeveloper.eslint.ESLintLanguageServer, sorry for this mistake. This PR the problem.
> Uncomment org.eclipse.wildwebdeveloper.eslint.ESLintLanguageServer

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
Remove the unused messages left after merge of #944 and #933 (https://github.com/eclipse/wildwebdeveloper/commit/fdc11540805e03fce597f50496a12e2a614f0c75)
> [cleanup] Cleanup XML UI Messages

- .github/workflows/licensecheck.yml
- Disables NPM Dependencies License check executon for ANY comment made on an issue or a PR The only `'/request-license-review` comment is used to start check and create IP Team review requests if needed
- Adds NPM Dependencies License check for JUnit test proects
> Fix NPM Dependencies License Check

- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
vscode-eslint  2.2.6  --> 2.3.0
eslint-server  2.2.5 --> 2.2.5
> Update LSs & NPM Modules - vscode-eslint 2.3.0 (pre-release)

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDAPDebugDelegate.java
> Can't launch/debug *.cjs files #958

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java
The automatic NGCC check is disabled for an Angular project
Issue: #836
> Angular Language Server popup error #836

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.3.0  --> 2.3.3
eslint-server  2.2.5 --> 2.3.3
> Update LSs & NPM Modules - vscode-eslint 2.3.3 (pre-release)

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
The TypeScript Language Server is set to use the WWD provided 'tsserver.js'
Issue: #1070
> Typescript analysis broken after update #1070

- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.75.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.13.0
> Update Embedded Node.js Runtime to latest LTS version (v.18.13.0)

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.76.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.14.2
> Update Embedded Node.js Runtime to latest LTS version (v.18.14.2)

- target-platform/target-platform.target
Hoping it fixes TestESLint failure
> Try LSP4E snapshots

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.15.0
> Update Embedded Node.js Runtime to latest LTS version (v.18.15.0)

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.3.3  --> 2.4.1
eslint-server  2.3.3  --> 2.3.3
> Update LSs & NPM Modules - vscode-eslint 2.4.1 (pre-release)

- org.eclipse.wildwebdeveloper/plugin.xml
This PR recovers some changes made pn content type mappings in https://github.com/eclipse/wildwebdeveloper/pull/1009/files#diff-39186773eb7c359cf334445a924d91bdb589ea566a6eba995f06cdf7af1e7d18
> Errors in tsx since upgrading to 1.0.0 #980

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
A JUnit test case is added for the issue
Issue: #1209
> [tests] Refactorings->Rename doesn't work for TypeScript files #1209

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/autoclose/XMLAutoCloseTagReconciler.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/autoinsert/HTMLAutoInsertReconciler.java
After `LanguageServiceAccessor.LSPDocumentInfo.getLanguageClient()` API is removed
> Fix API incompatibilities in latest o.e.lsp4e (v. >= 0.17)

- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package.json
Use the latest available @typescript-eslint modules
> [tests] Fix eslint test project

- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.79.0) extensions

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.4.1  --> 2.4.2
eslint-server  2.3.3  --> 2.4.1
> Update LSs & NPM Modules - vscode-eslint 2.4.2 (release)

- README.md
> Vue.js info on README

- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- repository/epp.product
- repository/pom.xml
LemMinX 0.27.0 is not API-compatible with 0.26 so extensions may not work properly.
> Use LemMinX 0.27.0

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
> Disable download external resources by default #1289

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.17.1
> Update Embedded Node.js Runtime to v.18.17.1 LTS

- org.eclipse.wildwebdeveloper/plugin.properties
- org.eclipse.wildwebdeveloper/plugin.xml
Create basic keywords for WWD preference pages
Same problems was for JavaScript, TypeScript, HTML, etc so I prepared some keywords for them
> Fix #1310 - preference pages are not found when searching for "yaml"

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/VSCodeJSDebugDelegate.java
The host name to use may depend on network settings (eg IPv4 vs IPv6), so instead of hardcoding it, we read it from the debug adapter output.
> [vscode-js-debug] Read host name from output

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/VSCodeJSDebugDelegate.java
Fixes https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1365
> Resolve ts->js mapping relative to rootDir

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/VSCodeJSDebugDelegate.java
> Use "outputCapture": "std" for Node launches

- org.eclipse.wildwebdeveloper/pom.xml
> Update VSCode (v.1.83.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.18.2
> Update Embedded Node.js Runtime to v.18.18.2 LTS

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/autoclose/XMLAutoCloseTagReconciler.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/autoinsert/HTMLAutoInsertReconciler.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/VueAutoInsertReconciler.java
Merge when new lsp4e version will be released with this commit: https://github.com/eclipse/lsp4e/commit/5aab9c628cfc276dd587d558753ef1019b204a6c
> Drop Thread.sleep from reconcilers

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.84.0
> Update VSCode (v.1.84.0) extensions

- Jenkinsfile
No any additional profile is supposed to be used for Mac-signing
> [build] Jenkinsfille contents is rolled back

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.10.0
> Update Embedded Node.js Runtime to v.20.10.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.85.0
> Update VSCode (v.1.85.0) extensions

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
See: https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1070#issuecomment-1872556578
> Fixed wrong path to tsserver

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.11.0
> Update Embedded Node.js Runtime to v.20.11.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.4.1  --> 2.4.3
eslint-server  2.3.3  --> 2.4.1
> Update vscode-eslint 2.4.3 (pre-release)

- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.4.1  --> 2.4.3
eslint-server  2.3.3  --> 2.4.1
> Update vscode-eslint 2.4.3 (pre-release) (Part 2)

- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.4.3  --> 2.4.4
eslint-server  2.4.1  --> 2.4.1
> Update vscode-eslint 2.4.4 (release)

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.11.1
> Update Embedded Node.js Runtime to v.20.11.1 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.86.0
> Update VSCode (v.1.86.0) extensions

- Jenkinsfile
- pom.xml
Renamed the maven profile to reflect the fact there is no more packing.
> Sign only master build

- Jenkinsfile
There are no products anymore.
Finishes https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1493
> Fix deploy step

- org.eclipse.wildwebdeveloper/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1505
> Force qualifier update

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.12.1
> Update Embedded Node.js Runtime to v.20.12.1 LTS

- pom.xml
Tycho to 4.0.7
Antrun to 3.1.0
> Update maven plugins versions

- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
> Bump o.e.wildwebdeveloper to 1.2.0

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.12.2
> Update Embedded Node.js Runtime to v.20.12.2 LTS

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- repository/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.89.0
> Update VSCode (v.1.89.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.13.1
> Update Embedded Node.js Runtime to v.20.13.1 LTS

- target-platform/target-platform.target
This is part of the jvm for ages.
> Remove unneeded javax.xml.stream from TP

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.90.0
> Update VSCode (v.1.90.0) extensions

- .github/dependabot.yml
More grouping for angular-app test project
> [nobug] Update dependabot - add npm groups

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.14.0
> Update Embedded Node.js Runtime to v.20.14.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.91.0
> Update VSCode (v.1.91.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.15.1
> Update Embedded Node.js Runtime to v.20.15.1 LTS

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
vscode-eslint  2.4.4  --> 3.0.11
eslint-server  2.4.1  --> 3.0.10
> Update vscode-eslint 3.0.11 (pre-release)

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
Reverts eclipse-wildwebdeveloper/wildwebdeveloper#1623
> Revert "Update vscode-eslint 3.0.11 (pre-release)"

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.92.0
> Update VSCode (v.1.92.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.16.0
> Update Embedded Node.js Runtime to v.20.16.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.93.0
> Update VSCode (v.1.93.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.17.0
> Update Embedded Node.js Runtime to v.20.17.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.94.0
> Update VSCode (v.1.94.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.18.0
> Update Embedded Node.js Runtime to v.20.18.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.95.0
> Update VSCode (v.1.95.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.11.0
> Update Embedded Node.js Runtime to v.22.11.0 LTS

- org.eclipse.wildwebdeveloper.tests/testProjects/vue-app/babel.config.js
- org.eclipse.wildwebdeveloper.tests/testProjects/vue-app/vue.config.js
Let's use the recommended ES modules in the vue test app.
> Apply vue ls updates to vue test project

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.12.0
> Update Embedded Node.js Runtime to v.22.12.0 LTS

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.96.0
> Update VSCode (v.1.96.0) extensions

- README.md
Fixes https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1747
> Standalone product has been removed, fix readme

- org.eclipse.wildwebdeveloper.xml/plugin.properties
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
PLEASE TEST before merging, I tried to setup WWD but got weird behavior. If you run this PR locally you should be able to find the preference page with the new keyword
> Adding search terms to the XML validation preference page

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.13.0
> Update Embedded Node.js Runtime to v.22.13.0 LTS

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.13.1
> Update Embedded Node.js Runtime to v.22.13.1 LTS

- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.97.0
> Update VSCode (v.1.97.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- repository/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.14.0
> Update Embedded Node.js Runtime to v.22.14.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.99.0
> Update VSCode (v.1.99.0) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.15.0
> Update Embedded Node.js Runtime to v.22.15.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.100.2
> Update VSCode (v.1.100.2) extensions

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.17.0
> Update Embedded Node.js Runtime to v.22.17.0 LTS

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.17.1
> Update Embedded Node.js Runtime to v.22.17.1 LTS

- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- repository/category.xml
- repository/pom.xml
They are to be deprecated in Tycho 5.
> Stop building source features

- Jenkinsfile
- docker/Dockerfile
* Fedora 42
* Maven 3.9.11
* NodeJS 22.18.0
> Update docker image used for build

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/autoclose/XMLAutoCloseTagReconciler.java
I've just been staring at this code for a few days and it's starting to bother me.
Should fix 1 warning
> Remove unused variable

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.19.0
> Update Embedded Node.js Runtime to v.22.19.0 LTS

- org.eclipse.wildwebdeveloper/pom.xml
Release notes: https://github.com/microsoft/vscode/releases/tag/1.104.0
> Update VSCode (v.1.104.0) extensions
