eclipse-wildwebdeveloper/wildwebdeveloper

- target-platform/target-platform.target
It was looking to `http://download.eclipse.org/eclipse/updates/4.8milestone` but that repository does not exist because Photon was released.
The new repository is at `http://download.eclipse.org/eclipse/updates/4.8/`
> Update target platform to photon

- org.eclipse.bluesky/language-servers/package.json
- org.eclipse.bluesky/pom.xml
- org.eclipse.bluesky/src/org/eclipse/bluesky/json/JSonLanguageServer.java
Hello @mickaelistria 
I updated the language servers from VS Code. I get some errors during the use of the html language server. 
For example: 
```
<html>
<head>
<style>|
</head>
<body>
</body>
</html>
```
When I invoke the completion where the | is present (| represent the caret) I get the following error. 
```
!ENTRY org.eclipse.lsp4e 4 0 2018-07-11 21:51:59.989
!MESSAGE org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
at …
```
> update language server

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
A simple (but powerful) way to allow the user to "select" the nodejs location.
The user can set  property `org.eclipse.wildwebdeveloper.nodeJSLocation` in the Eclipse.ini or in the command line parameters.
Product developers can set this property on the fly.
Signed-off-by: PhaserEditor2D <developers@phasereditor2d.com>
> NodeJS config: get the path from a system property

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
Fixes `Plugin org.eclipse.wildwebdeveloper.xml, extension org.eclipse.ui.editors: Unknown editor with id: org.eclipse.ui.genericeditor.GenericEditor` warning
Signed-off-by: Xi Yan <xixiyan@redhat.com>
> Update xml/MANIFEST.MF to include eclipse.ui.genericeditor

- org.eclipse.wildwebdeveloper/plugin.xml
As per https://code.visualstudio.com/docs/languages/json if you have
*.jsonc file it is treated as json with comments and warnings about
comment are not shown. Add association to have it by default.
> Support jsonc file types too.

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeAttachDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeRunDAPDebugDelegate.java
this prevents from noisy messages in console.
> Do not monitor Debug Adapter launcher process by default

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/HTMLLaunchableAdapterFactory.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/IsLaunchableHTMLTester.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDebugLaunchShortcut.java
Make both html projects and folder debuggable with Firefox and Chrome on right-click -> Debug as...
To be debugged, the project or folder must have either a index.html or a single .html file in it's root.
Fix #258
> Make html projects debuggable with Firefox/Chrome on right-click menu

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
This is a follow up to #238. Indeed, Wild Web Developer does not work properly on my macOS Mojave machine. Node.js 10.16.3 is part of my `PATH` variable specified in my _.profile_ file, however, as documented [here](https://stackoverflow.com/a/55716895/3527464), the `-l` option needs to be specified to make sure it is picked up when executing the shell from within Eclipse.
Signed-off-by: PyvesB <PyvesDev@gmail.com>
> Make bash act as if invoked as a login shell

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java
If 'which' yields a positive result then we know that the exe
exists and there no need to test it again for existance.
Signed-off-by: Mat Booth <mat.booth@redhat.com>
> Avoid double-testing for node's existance.

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java
Closes  #309. Note that underneath the hood, the program is launched in a background job, so this change should not impact UI responsiveness.
> Call DebugUITools.launch from the UI thread

- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
* Update cbi plugin to 1.1.7
* Define single download-maven-plugin and use it everywhere instead of
each plugin using different version
* Update download-maven-plugin to 1.5.0
> Maven builds updates

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper/pom.xml
- pom.xml
As most embedded deps are configured in pom.xml and the pom files don't
change much otherwise, let's take the pom.xml into account for qualifier
computation so important changes lead to new version (preventing from
further baseline replacement).
Also remove package-lock.json on clean.
> Account pom.xml change in qualifier computation

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
set the right nodePath (should be a (parent) dir that has the
node_modules that has again eslint)
set the workingFolder (for now the highest folder with a package.json)
and set the workingDirectory property in auto mode so eslint server will
try to find the best location of the eslint config file for the given
file.
> Fixes for the ESLint vscode intergration

- Jenkinsfile
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/Activator.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/MessageUtils.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/firefox/FirefoxRunDABDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/messages.properties
When Chrome/Firefox Debug launch is created, the only browser defined in 'Run with:` field of launch configuration is to be used to start debuging. So, no any additional searches for a browser executable to be performed.
If no browser is confiured, a message is displayed prompting a user to open Launch Configuration Browser Tab or Web Browser preference page to configure/select a correct browser.
Firefox Debug is also updated to serach fora browser executable in a list of browsers defined in Web Browser preference page.
If no executable can be found it is suggested to open Web Browser preference page to add/edit Firefox browser location.
Fixes: #588
> Chrome Debug Fails to Start #588

- docker/Dockerfile
This means Node.js switches from 12 to 14 and we would better run our
tests with latest LTS version.
> Update to Fedora 33 docker image

- org.eclipse.wildwebdeveloper/pom.xml
update to the latest esLint server of vscode, the previous problem of 2.1.13 seems to be fixed in this .14 release
> upgraded esLint server (vscode) to version 2.1.14

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServerExtention.java
- repository/epp.product
added json request/notifications for:
projectLoadingStart, projectLoadingFinish, projectLanguageService,
suggestIvyLanguageServiceMode, suggestStrictMode and implemented
notifyProgress
For now these all just log, but suggestIvyLanguageServiceMode should
give the user an option (or point to an option) to enable the
commands.add("--experimental-ivy");
in the AngularLanguageServer
(this should i think be a setting in the preferences)
Problem is a bit if you enabled this now that you get many exception in
the log because of: https://github.com/eclipse/lsp4j/issues/479
Signed-off-by: Johan Compagner <jcompagner@gmail.com>
> implemented a LanguageClientImpl for angular

- org.eclipse.wildwebdeveloper/plugin.xml
`.cjs` and `.mjs` are two variants of the standard `.js` JavaScript file extension, which can be used to differentiate between the CommonJS and ESM module systems. More information can be found in the [Node.js documentation](https://nodejs.org/docs/latest/api/packages.html#determining-module-system).
> Support .cjs and .mjs JavaScript extension variants

- Jenkinsfile
- docker/Dockerfile
- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/build.properties
- org.eclipse.wildwebdeveloper.tests/plugin.xml
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper/.gitignore
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YamlLanguageClientImpl.java
Output of Dash License Tool
```
main] INFO Querying Eclipse Foundation for license data for 168 items.
[main] INFO Found 7 items.
[main] INFO Querying ClearlyDefined for license data for 162 items.
[main] INFO Found 162 items.
License information could not be automatically verified for the following content:
npm/npmjs/-/less/4.1.2
npm/npmjs/-/prettier/2.0.5
npm/npmjs/-/sass/1.43.4
npm/npmjs/-/typescript/4.4.4
npm/npmjs/-/vscode-json-languageservice/4.1.9
npm/npmjs/-/yaml-language-server/1.1.0
npm/npmjs/@angular/language-server/12.2.2
This content is either not correctly mapped by the system, or requires review.
Setting up a review for npm/npmjs/-/vscode-json-languageservice/4.1.9.
- Created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/1522
Setting up a review for …
```
> Update Language Servers

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLCatalogs.java
fix for #756
ensure URI is encoded for any file that ends up having a space (or other character needing encoding)
> XMLCatalogs #756 encode URIs to avoid errors if file used for extracted xml catalog has spaces (or similar)

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.13.2
> Update Embedded Node.js Runtime to latest LTS version (v.16.13.2)

- org.eclipse.wildwebdeveloper/plugin.xml
JSX and TSX are extensions of JS and TS respectively, it makes sense to use their icons rather than falling back to the default generic editor icon.
> Use JS and TS icons for JSX and TSX content types

- org.eclipse.wildwebdeveloper/plugin.xml
In the [`org.eclipse.core.contenttype.contentTypes` extension point](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_core_contenttype_contentTypes.html), the `file-extensions` attribute must not contain `.` and `*` since _extension_ means here the string after the last `.` and the `file-names` attribute does not support the `*` wildcard in contrast to the `file-patterns` attribute.
Examples:
- `file-extensions="eslintrc"` matches the following file names: `.eslintrc`, `foo.eslintrc`, etc.
- `file-patterns="*.eslintrc.json"` matches the following file names: `.eslintrc.json`, `foo.eslintrc.json`, etc.
- `file-extensions="eslintrc.json"` does not match any filename
> Correct file extensions/names/patterns: ESLint, TypeScript config/lint

- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
The `org.eclipse.tm4e.languageconfiguration` is required for the `org.eclipse.tm4e.languageconfiguration.languageConfigurations`
extension point and to avoid errors in the preferences _Text Mate > Language Configuration_ when e.g. in the Eclipse SDK, only the _Wild Web Developer XML tools_ feature is installed.
See also [commit 76a939bdf0fc9d06d5cf2f51fa9971c6d4a06777](https://github.com/eclipse/wildwebdeveloper/commit/76a939bdf0fc9d06d5cf2f51fa9971c6d4a06777)
> XML: Add dependency to org.eclipse.tm4e.languageconfiguration

- Jenkinsfile
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- repository/epp.product
- repository/pom.xml
Github project credentials are to be used in `wget` action when accessing
`https://raw.githubusercontent.com` in order to minimize restriction limits
> Fix github credencials

- Jenkinsfile
- org.eclipse.wildwebdeveloper/pom.xml
Github project credentials are to be used in `wget` action when accessing
`https://raw.githubusercontent.com` in order to minimize restriction limits
> Fix github credencials (pass 2)

- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebug.java
node-debug doesn't react well to "destroy". LSP4E fixes it later with
https://github.com/eclipse/lsp4e/pull/122 , but in the meantime, we need
a workaround.
> Kill zombie process in tests

- Jenkinsfile
- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.14.2
> Update Embedded Node.js Runtime to latest LTS version (v.16.14.2)

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServerExtention.java
A default implementation is added for the `angular/NgccProgressEnd` notification method
> WARNING: Unsupported notification method: angular/NgccProgressEnd #832

- org.eclipse.wildwebdeveloper/pom.xml
Error:  Failed to execute goal org.apache.maven.plugins:maven-scm-plugin:2.0.0-M2:checkout (fetch-eslint-ls-package.json) on project org.eclipse.wildwebdeveloper: Error found while cleaning up output directory base on excludes/includes configurations. Unable to delete file D:\a\wildwebdeveloper\wildwebdeveloper\org.eclipse.wildwebdeveloper\target\vscode-eslint-ls\extension\.git\objects\pack\pack-6cb8a8d36f90b73a38727f3ab60525b73319a8f4.idx
> Fix failure on fetching the ESLint LS package.json file

- org.eclipse.wildwebdeveloper/pom.xml
firefox-debugadapter          2.9.6  --> 2.9.8
> Update LSs & NPM Modules - firefox-debugadapter 2.9.8

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLCatalogs.java
Fixed: NullPointer in Wild Web Developer causes POM editor to stop functioning after installing specific plugin #897
> Fixed: Issue #897

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.17.1
> Update Embedded Node.js Runtime to latest LTS version (v.16.17.1)

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.xml/grammars/dtd/dtd.tmLanguage.json
- org.eclipse.wildwebdeveloper.xml/grammars/rnc/rnc.tmLanguage.json
- org.eclipse.wildwebdeveloper.xml/language-configurations/rnc/rnc.language-configuration.json
- org.eclipse.wildwebdeveloper.xml/plugin.xml
This PR provides
* syntax coloration for DTD
* syntax coloration + language configuration for RelaxNG compact syntax
* Defines the RNG (RelaxNG XML syntax) , RNC (RelaxNG compact syntax) content type.
* Bind RNG files with XML language server to support RelaxNG validation/completion, hover for a RelaxNG RNG grammar file. This feature will be available when LemMinx release (which sould come from today I hope) will be embed in WWD.
If you don't know about RelaxNG, see the vscode-xml documentation at https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/RelaxNGFeatures.md and in https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/RelaxNGFeatures.md#creating-xml-rng-rnc-files you have samples of RNG, RNC and XML validated by RelaxNG files.
> Syntax coloration / language config for DTD, RelaxNG

- .github/workflows/licensecheck.yml
- .github/workflows/windowsPR.yml
Also moved distribution from 'adopt' to 'temurin' -
see: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
> Fix absent distribution param in setup-java in WindowsPR

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper/plugin.properties
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/CSSLanguageClient.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/CSSLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSCompletionPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSFormatPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSHoverPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSPreferenceInitializer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/CSSValidationPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/ValidPropertiesFieldEditor.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSCompletionPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSFormatPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSHoverPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/less/LESSValidationPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSCompletionPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSFormatPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSHoverPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/preferences/scss/SCSSValidationPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/ui/preferences/Settings.java
> CSS, LESS, SCSS preferences

- RELEASE_NOTES.md
- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/plugin.xml
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/commands/AssociateGrammarDialog.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/commands/AssociateGrammarHandler.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/Messages.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLCatalogPreferencePage.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
This PR provides the capability to associate an XML file with a XSD, DTD, RelaxNG grammar file easily by clicking on the CodeLens. See the following demo:
> Associate grammar file with CodeLens

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeRunDAPDebugDelegate.java
Fixes #971
---
Note that I did look into replacing Gson with another parser (I gave [Jackson](https://github.com/FasterXML/jackson) a try), but it turns out that Gson is used not only in WWD, but across the LSP4E and TM4E projects, which all pass Gson objects between each other.  Replacing Gson would thus take a bit of coordination across all three projects.
Plus, the libraries of whatever new parser is used would have to be provided in WWD's Eclipse repository, as Gson currently is.
So for now, just doing some manual parsing should be the least disruptive solution for the filed issue.
Also note that the comment-stripping isn't strictly necessary (as Gson's default configuration accepts comments), but it helps with handling comments that follow a trailing comma.
> Allow tsconfig.json to have trailing commas

- org.eclipse.wildwebdeveloper.tests/.classpath
- org.eclipse.wildwebdeveloper.tests/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.tests/pom.xml
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
Due to change in  `typescript-language-server@2.2.0` that implements `prepareRename` request now we have to implicitly set the new value for an identofier im `Refactoring->Rename` dialog during the test.
See: [`feat: support textDocument/prepareRename request #628` change](https://github.com/typescript-language-server/typescript-language-server/pull/628)
> Fix JS/TS Refactoring Rename JUnit Test

- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
LemMinX 0.23 is API-compatible with 0.22 so extensions are still working.
> Use LemMinX 0.23

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/Messages.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/PreserveSpaceFieldEditor.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLFormattingPreferencePage.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceInitializer.java
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceServerConstants.java
- org.eclipse.wildwebdeveloper/plugin.xml
New XML format settings
Here a screenshot will all missing settings coming from the new formatter:
Label should be revisisted because some label are too long (any review are welcome), but I did that quickly .
> New XML format settings

- .github/workflows/licensecheck.yml
Only libraries we're developing, shipping or requiring for Wild Web Developer to work well need to have IP checked.
Dependencies in tests, that we download dynamically during test execution, are exempt.
> Do not check IP for deps in tests

- org.eclipse.wildwebdeveloper/plugin.xml
'Unknown at rule' on file extensions associated with content type LESS
Fixes #1017
> 'Unknown at rule' on file extensions associated with content type LESS

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageClientImpl.java
Feb 07, 2023 1:10:48 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/typescriptVersion
> Fix Unsupported notification method: $/typescriptVersion

- TIPS_and_FAQ.md
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
Builds off the https://github.com/eclipse/wildwebdeveloper/discussions/974  discussion
> Add note on debugger / logging usage in XML LS

- README.md
The [Marketplace entry](https://marketplace.eclipse.org/content/wild-web-developer-html-css-javascript-typescript-nodejs-angular-json-yaml-kubernetes-xml) seems to have changed, maybe due to the 1.0.0 release.
> README.md: Update installation/download links

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServerExtension.java
Mar 18, 2023 5:11:41 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint request WARNING: Unsupported request method: eslint/noConfig
> Fix "Unsupported request method: eslint/noConfig" error

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.0
> Update Embedded Node.js Runtime to v.18.16.0 LTS

- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
LemMinX 0.24 is API-compatible with 0.23 so extensions are still working.
> Use LemMinX 0.24

- Jenkinsfile
- docker/Dockerfile
- docker/README.md
There is "Unsupported engine" error message during the tests projects setup:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@9.1.1',
npm WARN EBADENGINE   required: { node: '14 || >=16.14' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '9.5.1' }
npm WARN EBADENGINE }
```
> [tests] Use Node v.18.16.0 on Jenkins

- docker/Dockerfile
due to the following build errors:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT:process (default-process) on project org.eclipse.wildwebdeveloper.embedder.node: The plugin org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT requires Maven version 3.8.6 -> [Help 1]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT:process (default-process) on project org.eclipse.wildwebdeveloper.xml: The plugin org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT requires Maven version 3.8.6 -> [Help 1]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT:process (default-process) on project org.eclipse.wildwebdeveloper.product.branding: The plugin org.eclipse.tycho:tycho-bnd-plugin:4.0.0-SNAPSHOT requires Maven …
```
> [build] Fixed docker image to provide maven v.3.9.2

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
This PR contains an enhancement of tsx test to verify fix for https://github.com/eclipse/wildwebdeveloper/issues/980
> Enhanced language server TSX test to verify functionality on xml notation

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.1
> Update Embedded Node.js Runtime to v.18.16.1 LTS

- org.eclipse.wildwebdeveloper.xml/pom.xml
LemMinX 0.26.1/0.26.0 is not API-compatible with 0.25 so extensions may not work properly.
> Use LemMinX 0.26.1

- org.eclipse.wildwebdeveloper/plugin.xml
> Fix #1290 - No grammar provided for <vue.sfc.style.variable.injections>

- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/preferences/XMLPreferenceServerConstants.java
```
Aug 10, 2023 6:57:30 AM org.eclipse.lemminx.settings.FaultTolerantTypeAdapterFactory$1 read
WARNING: Encountered an invalid setting. Using the default value. Please check your settings for outdated or invalid settings.
java.lang.IllegalStateException: Expected STRING but was BOOLEAN at path $.validation.schema.enabled
Aug 10, 2023 6:57:30 AM org.eclipse.lemminx.settings.FaultTolerantTypeAdapterFactory$1 read
WARNING: Encountered an invalid setting. Using the default value. Please check your settings for outdated or invalid settings.
java.lang.IllegalStateException: Expected STRING but was BOOLEAN at path $.validation.namespaces.enabled
```
> Fix Lemminx LS reported configuration setting errors

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/preferences/JSTSPreferenceInitializer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/preferences/JSTSPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/preferences/JSTSPreferenceServerConstants.java
Until now, the TypeScript version was systematically being overridden to point to the one packaged with Eclipse. This meant that if your project relied on a different version of TypeScript (as specified in `package.json` for example), there was a risk of incompatibilities. Even worse, custom type definitions brought in third party dependencies were not resolved properly, for example in the case of React.js:
VSCode allows switching between either its own version of TypeScript, or the one specified by the project, as described here:
https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript
This PR adds similar support to Eclipse, via a preference page option. The default is the same as before, i.e. TypeScript packaged with Eclipse, so the …
> Allow using TypeScript version specified by project

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDAPDebugDelegate.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/chrome/ChromeRunDebugTabGroup.java
The "vscode-chrome-debug" debugger can either be instructed to start chrome from a specific path or it can try to locate chrome itself. See here: https://github.com/microsoft/vscode-chrome-debug/blob/master/src/chromeDebugAdapter.ts
If going for the first option the `runtimeExecutable` parameter must be specified. This is what wwd currently does and what causes #1327
In contrast, here is a typical `launch.json` from VSCode: 
```
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"type": "chrome",
"request": "launch",
"name": "Launch Chrome against localhost",
"url": "http://localhost:4200/",
"webRoot": …
```
> #1327 A "Chrome Debug" session can now be started even when a chrome window is already open

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/AllCleanRule.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestVue.java
- org.eclipse.wildwebdeveloper.tests/testProjects/vue-app/src/App.vue
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/VueLanguageServer.java
Real fix is in TestVue.java (-1 is no longer required)
In the meantime I also updated server and remove unnecessary System.out.println
> Fix #1316 - Vue.JS tests failures

- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/VueLanguageServer.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/VueLanguageServerAPI.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/AutoInsertLastChange.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/AutoInsertOptions.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/AutoInsertParams.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/AutoInsertResponse.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/vue/autoinsert/VueAutoInsertReconciler.java
I started from AutoInsert reconciler, but as the result , there is a quiet big path:
1. AutoInsert support
2. Original VSCode preferences mapper (plus registered preferences in Eclipse) - I'm reading descriptions and types from vscode plugin package.json and map to IEclipsePreferences
3. Vue server can consume preferences from CSS/HTML/JS/TS and probably others (see fallbackCollect)
4. Special map for "typescript-server" settings to vscode settings aliases (vue require names as in vscode settings.json)
5. typescript-server-vue plugin
In general, preference support is nighmare. If server can consume extra preferences, each section server have to be mapped manually. I think this should be somehow pluggable, probably on LSP4E level
> Fix #1332 - Add autoinsert support

- .github/workflows/MacOsPR.yml
- .github/workflows/windowsPR.yml
- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/pom.xml
Test PR, I'm trying to stabilize tests
> Fix github workflows

- org.eclipse.wildwebdeveloper/package.json
Just add to package.json, with force will be installed even on linux/windows
> Fix #1343 - add fsevents for MacOS users

- org.eclipse.wildwebdeveloper.embedder.node.feature/feature.xml
- org.eclipse.wildwebdeveloper.embedder.node.feature/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestVue.java
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/npm/NpmLaunchDelegate.java
Introduce NodeJSManager helpers to always produce ProcessBuilder with commands:
node_executable npm_location rest commands
these command is also used in NpmLaunchDelegate!
> Fix #1247 - Maven build use node from PATH on mac os

- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.linux.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.aarch64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/nodejs-info.properties
- org.eclipse.wildwebdeveloper.embedder.node.win32.x86_64/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.18.0
> Update Embedded Node.js Runtime to v.18.18.0 LTS

- org.eclipse.wildwebdeveloper.feature/feature.xml
- org.eclipse.wildwebdeveloper.feature/pom.xml
- org.eclipse.wildwebdeveloper/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper/pom.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/Messages.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/messages.properties
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/preferences/JSTSPreferencePage.java
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/ui/preferences/JSTSPreferenceServerConstants.java
- repository/epp.product
- repository/pom.xml
By default, the ESLint language server will try to find the ESLint package in `node_modules` at the root of the project. However, it may be in a different place, for example when using non-NPM package managers. This PR adds a preference to configure the location.
I've added the new preference to the existing JS/TS preferences page. Even though a different language server, ESLint is strongly tied to JS and TS, it didn't feel right to introduce a separate bespoke page just for this preference.
> Allow configuring directory of ESLint package

- target-platform/target-platform.target
Wikitext update site https://download.eclipse.org/mylyn/docs/releases/ doesn't ptovide the latest version by default, so it needs to either point to a certain version (and update on the regular baasis) or switch it to be downloaded from the latest Eclipse release (to use the same version as the one used in  Eclipse release)
> [build] Use wikitext feature from Eclipse releases

- pom.xml
* upgrade minimum Maven version, Tycho 4 requires 3.9
* upgrade Tycho itself. why didn't dependabot do this?
* remove invalid resolver configuration
> Upgrade Tycho

- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/ui/messages.properties
before
and after
Checkboxes (on Windows) don't have multiline text, at least not without additional magic, therefore the newline is invalid there.
> Fix preferences layout

- Jenkinsfile
- docker/Dockerfile
Aligns the node.js version with the one shipped in embedder. Uses Fedora 39 default JVM.
> Update docker image in buld to use Java 21 and Node.js 20

- Jenkinsfile
Hopefully this reduces(removes even) the pletora of "Failure executing: POST at: https://10.30.0.1:443/api/v1/namespaces/wildwebdeveloper/pods. Message: pods "wildwebdeveloper-buildtest-pod-1f87z-kqc01" is forbidden: exceeded quota: jenkins-instance-quota, requested: limits.memory=6400Mi,requests.memory=6400Mi, used: limits.memory=7936Mi,requests.memory=7936Mi, limited: limits.memory=10Gi,requests.memory=10Gi. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=wildwebdeveloper-buildtest-pod-1f87z-kqc01, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "wildwebdeveloper-buildtest-pod-1f87z-kqc01" is forbidden: exceeded quota: jenkins-instance-quota, requested: …
> Reduce Jenkinsfile requested resources to 4Gi

- org.eclipse.wildwebdeveloper.embedder.node/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.embedder.node/pom.xml
- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/CompressUtils.java
- target-platform/target-platform.target
Commons-compress deprecated its own IOUtils in favor of commons-io thus code is migrated accordingly.
> Update commons-compress to 1.26.0

- target-platform/target-platform.target
* Use released lsp4e.
* Use gson from Eclipse platform rather than define again.
> Streamline target platform

- target-platform/target-platform.target
They are not directly used in the codebase thus are better fetched by whatever requires them.
> Remove jakarta APIs from target platform

- pom.xml
The config for signing only makes it suspect for
https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1505 .
> Let Tycho handle metadata with default

- org.eclipse.wildwebdeveloper.xml/pom.xml
The lemminx language server in version 0.27.0 throws a nasty error in some cases (see https://github.com/eclipse/lemminx/issues/1653) that has been fixed on 0.28.0, so updating to that version would be awesome.
> update lemminx to 0.28.0

- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAngular.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestDebug.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestHTML.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJSON.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestJsTs.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestLanguageServers.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestSyntaxHighlighting.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestVue.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestXML.java
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestYaml.java
Get rid of all the anonymous classes generated.
> Use lambda methods of DisplayHelper

- org.eclipse.wildwebdeveloper/plugin.xml
Vitepress for example uses `config.mts` when TypeScript is enabled.
See also https://www.totaltypescript.com/concepts/mjs-cjs-mts-and-cts-extensions
> Register .cts and .mts file extensions with TypeScript content type

- org.eclipse.wildwebdeveloper.embedder.node/src/org/eclipse/wildwebdeveloper/embedder/node/NodeJSManager.java
Use the readers directly instead of manually creating readers on top of the process's streams.
> Simplify Process streams handling

- Jenkinsfile
Removes
```
[WARNING]  Parameter 'passphrase' (user property 'gpg.passphrase') is
deprecated: Do not use this configuration, it may leak sensitive
information. Rely on gpg-agent or env variables instead.
[WARNING]
[WARNING] W A R N I N G
[WARNING]
[WARNING] Do not store passphrase in any file (disk or SCM repository),
[WARNING] instead rely on GnuPG agent or provide passphrase in
[WARNING] MAVEN_GPG_PASSPHRASE environment variable for batch mode.
[WARNING]
[WARNING] Sensitive content loaded from Mojo configuration
```
from the build output.
> Fix build warning with latest tycho/maven-gpg-plugin

- org.eclipse.wildwebdeveloper.tests/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.wildwebdeveloper.xml.feature/feature.xml
- org.eclipse.wildwebdeveloper.xml.feature/pom.xml
- org.eclipse.wildwebdeveloper.xml/META-INF/MANIFEST.MF
- org.eclipse.wildwebdeveloper.xml/build.properties
- org.eclipse.wildwebdeveloper.xml/pom.xml
- org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java
- target-platform/target-platform.target
Currently lemminx is embedded into WWD what has some disadvantages:
- the jar gets bigger
- the embedded jar needs to be extracted before it can be used
- version bumps are required for lemminx updates
- lemminx can't be updated independent from WWD
This now adds a require-bundle to the manifest (so we are getting a certain version we are compatible with) and uses the bundle wiring to get hold of the bundle and then transform it into a file path.
As discused here 
- https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/discussions/1712
> Consume lemminx as a bundle from the OSGi runtime

- org.eclipse.wildwebdeveloper.tests/testProjects/eslint/package.json
Without it, we get dependabot warnings "Dependabot does not support your npm version. Because of this, Dependabot cannot update this pull request."
> Explicitly add packageManager to package.json to help dependabot

- repository/category.xml
With the latest release I noticed that the update site actually is missing the `org.eclipse.lemminx.uber-jar` what makes PDE complain:
```
Cannot complete the install because one or more required items could not be found.
Cannot satisfy dependency:
From: Wild Web Developer XML tools 1.3.7.202501161210 (org.eclipse.wildwebdeveloper.xml.feature.feature.group 1.3.7.202501161210)
To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.xml [1.3.7.202501161210,1.3.7.202501161210]
Missing requirement: XML support using Language Server 1.3.7.202501161210 (org.eclipse.wildwebdeveloper.xml 1.3.7.202501161210) requires 'osgi.bundle; org.eclipse.lemminx.uber-jar [0.29.0,1.0.0)' but it could not be found
Software being installed: Wild Web Developer XML tools 1.3.7.202501161210 …
```
> Add org.eclipse.lemminx.uber-jar to the dependencies for category.xml

- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/ui/messages.properties
Fixes https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1813
> Remove irrelevant mention of VSCode in CSS prefs

- .github/workflows/licensecheck.yml
When re-starting the license check jobs, it may result into the following failure:
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
> Fix license check artifact upload error

- .github/dependabot.yml
- .gitignore
- README.md
- org.eclipse.wildwebdeveloper.tests/.project
- org.eclipse.wildwebdeveloper.tests/.settings/org.eclipse.m2e.core.prefs
- org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestAstro.java
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/.gitignore
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/.project
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/astro.config.mjs
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/package.json
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/src/layouts/base.astro
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/src/pages/index.astro
- org.eclipse.wildwebdeveloper.tests/testProjects/astro-app/tsconfig.json
- org.eclipse.wildwebdeveloper/package.json
- org.eclipse.wildwebdeveloper/plugin.xml
- org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/astro/AstroLanguageServer.java
This PR integrates the  [Astro](https://astro.build) language server into WildWebDeveloper and enables syntax highlighting of *.astro files via TM4E.
**Why to add Astro support?**
[Core Web Vitals - Technology Report](https://lookerstudio.google.com/u/0/reporting/55bc8fad-44c2-4280-aa0b-5f3f0cd3d2be/page/M6ZPC?params=%7B%22df44%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580React%25EE%2580%2580Vue.js%25EE%2580%2580Next.js%25EE%2580%2580Angular%25EE%2580%2580Nuxt.js%25EE%2580%2580Astro%25EE%2580%2580SvelteKit%22%7D):
[GitHub Star History](https://www.star-history.com/#withastro/astro&vuejs/core):
> Add Astro web framework support
